#!/bin/sh

# protoxid

function ctridx() {
  local myxuidhash="$(/home/luxcium/ahmyzsh/plugins/bin/randx 10)"
  local myxuiddate="$(date --utc +%C%y%m%d%H%M%S)$(date --utc +%N | cut -c -3)"
  local fooY="${myxuidhash}UXZ${myxuiddate}KK"
  local fooZ="${fooY:0:1}${fooY:13:2}${fooY:1:1}${fooY:15:2}${fooY:2:1}${fooY:17:2}${fooY:3:1}${fooY:19:2}${fooY:4:1}${fooY:21:2}${fooY:5:1}${fooY:23:2}${fooY:6:1}${fooY:10:2}${fooY:30:2}${fooY:12:1}${fooY:7:1}${fooY:25:2}${fooY:8:1}${fooY:27:3}${fooY:9:1}"
  echo -n $fooZ
}

function ctrlsum() {

  local myxuidhash="$(/home/luxcium/ahmyzsh/plugins/bin/randx 10)"
  local myxuiddate="$(date --utc +%C%y%m%d%H%M%S)$(date --utc +%N | cut -c -3)"
  local fooX3="${myxuidhash}UXZ${myxuiddate}KK"

  local fooY=""
  local cvalueX=0
  local firstmoduloX=0
  local secondmoduloX=0
  local modfstX=0
  local modsndX=0

  local cvalueY=0
  local firstmoduloY=0
  local secondmoduloY=0
  local modfstY=0
  local modsndY=0

  for ((i = 0; i < ${#fooX3}; i++)); do
    cvalueX=$(printf %d\\n \'$(echo -n "${fooX3:$i:1}"))
    firstmoduloX=$((($firstmoduloX + $cvalueX)))
    secondmoduloX=$((($secondmoduloX + (($firstmoduloX % 10)))))
  done

  modfstX=$((($firstmoduloX % 10)))
  modsndX=$((($secondmoduloX % 10)))

  fooY="$fooX3$modfstX$modsndX"

  for ((i = 0; i < ${#fooY}; i++)); do
    cvalueY=$(printf %d\\n \'$(echo -n "${fooY:$i:1}"))
    firstmoduloY=$((($firstmoduloY + $cvalueY)))
    secondmoduloY=$((($secondmoduloY + (($firstmoduloY % 10)))))
  done

  modfstY=$((($firstmoduloY % 10)))
  modsndY=$((($secondmoduloY % 10)))

  if [[ $modfstX$modsndX = $modfstY$modsndY ]]; then

    local fooZ="${fooY:0:1}${fooY:13:2}${fooY:1:1}${fooY:15:2}${fooY:2:1}${fooY:17:2}${fooY:3:1}${fooY:19:2}${fooY:4:1}${fooY:21:2}${fooY:5:1}${fooY:23:2}${fooY:6:1}${fooY:10:2}${fooY:30:2}${fooY:12:1}${fooY:7:1}${fooY:25:2}${fooY:8:1}${fooY:27:3}${fooY:9:1}"
    echo -n $fooZ
  fi
}
ctridx
exit 0
