echo "${BEGIN_SOURCING:=\u001b[0m\u001b[34m #} ${0} ZSHENV ${END_SOURCING:=\u001b[31;1m}"
#$ Verry first entry point !!!
#$ Interactive,Script,login,non-login

export AHMYZSH="${HOME}/ahmyzsh"
. "${AHMYZSH}/LOAD_ENV.zsh"
init_all
