#! /bin/env zsh

: ${HOME:="/home/luxcium"}
: ${AHMYZSH:="${HOME}/ahmyzsh"}
: ${CUSTOM_ZSH:="${AHMYZSH}/custom-zsh"}
: ${CUSTOM_ZSH_BIN:="${CUSTOM_ZSH}/bin"}
: ${POMODORO:="${CUSTOM_ZSH_BIN}/pomodoro.zsh"}

. ${POMODORO}

maxipomodoro60m_

exit 0
