source "${AHMYZSH}/themes/colors.sh"
export TIME_TO_PATH_STR="${TIME_TO_PATH} ms  to  'PATH'"

# echo -e "${LGNS}1-------10--------20--------30--------40--------50--------60--------70--------80${CE}"
BCOL="${BS}     ${COL}     "
COLB="${COL}     ${BS}     "
echo -e "${BCOL}${BCOL}${BCOL}${BCOL}${BCOL}${BCOL}${BCOL}${BCOL}${CE}"
echo -e "$COL          ${BS}${TIME_TO_PATH_STR}$COL                                                  ${CE}"
echo -e "$COL         █████╗ ██╗  ██╗  ███╗   ███╗██╗   ██╗  ███████╗███████╗██╗  ██╗        ${CE}"
echo -e "$COL        ██╔══██╗██║  ██║  ████╗ ████║╚██╗ ██╔╝  ╚══███╔╝██╔════╝██║  ██║        ${CE}"
echo -e "$COL        ███████║███████║  ██╔████╔██║ ╚████╔╝     ███╔╝ ███████╗███████║        ${CE}"
echo -e "$COL        ██╔══██║██╔══██║  ██║╚██╔╝██║  ╚██╔╝     ███╔╝  ╚════██║██╔══██║        ${CE}"
echo -e "$COL        ██║  ██║██║  ██║  ██║ ╚═╝ ██║   ██║     ███████╗███████║██║  ██║        ${CE}"
echo -e "$COL        ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═╝     ╚═╝   ╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝        ${CE}"
echo -e "$COL         ${WHS}by${COL} ${YS}Luxcium${COL}                                                             ${CE}"
echo "$RS                                                  Scientia es lux principium™   ${CE}"
# echo -e "${YS}# ${COL}>  ${LGNS}---10--------20--------30--------40--------50--------60--------70--------80${CE}"
# Scientia es lux principium
