# export CUSTOM_TMUX="<PATH TO CUSTOM_TMUX>"
# export CUSTOM_TMUX="${CUSTOM_TMUX}"
export TMUX_LIB="${CUSTOM_TMUX}/lib"
export TMUX_BIN="${CUSTOM_TMUX}/bin"

export TMUX_LIB_FNCT="${TMUX_LIB}/functions"
export TMUX_CONFIGS="${CUSTOM_TMUX}/configs"
export TMUX_POWERLINE="${CUSTOM_TMUX}/powerline"
export TMUX_FUNCTIONS="${CUSTOM_TMUX}/tmux-functions"
export TMUX_LIB_FNCT_MAIN="${TMUX_LIB}/tmux-functions.sh"

export TMUX_FUNCTIONS_INDEX="${TMUX_FUNCTIONS}/index.sh"
export PWRLN_TMUX_CONF="${PWRLN_BINDINGS}/tmux/powerline.conf"
export TMUX_LOADER="${TMUX_LIB}/tmux-loader.sh"
export TMUX_COMMON_CONF="${TMUX_CONFIGS}/common.tmux.config"
export TMUX_COMMON_THEME="${TMUX_CONFIGS}/theme.tmux.config"
export TMUX_ALIASES="${CUSTOM_TMUX}/tmux-aliases.sh"
