#!/bin/bash

# Script to create an inventory of all aliases in the aliases folder

ALIASES_DIR="/projects/templates/ahmyzsh/core/aliases"
OUTPUT_FILE="${ALIASES_DIR}/00000-alias-inventory.md"

# Header for the inventory file
echo "# Complete Alias Inventory" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Generated on: $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Summary of Alias Files" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "| Filename | Lines | Size (bytes) | Aliases Count |" >> "$OUTPUT_FILE"
echo "|----------|-------|-------------|---------------|" >> "$OUTPUT_FILE"

# Process all alias files
total_aliases=0
total_lines=0
total_size=0

for file in "${ALIASES_DIR}"/*.sh; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    lines=$(wc -l < "$file")
    size=$(wc -c < "$file")
    alias_count=$(grep -c "^alias " "$file")

    echo "| $filename | $lines | $size | $alias_count |" >> "$OUTPUT_FILE"

    total_aliases=$((total_aliases + alias_count))
    total_lines=$((total_lines + lines))
    total_size=$((total_size + size))
  fi
done

# Add totals
echo "| **TOTAL** | **$total_lines** | **$total_size** | **$total_aliases** |" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Now create detailed section for each file
echo "## Detailed Alias Listing" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for file in "${ALIASES_DIR}"/*.sh; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    echo "### $filename" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "Lines: $(wc -l < "$file") | Size: $(wc -c < "$file") bytes" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "| Alias | Command |" >> "$OUTPUT_FILE"
    echo "|-------|---------|" >> "$OUTPUT_FILE"

    # Extract aliases and their commands
    grep "^alias " "$file" | while read -r alias_line; do
      # Extract the alias name and command
      if [[ $alias_line =~ ^alias\ ([^=]+)=[\'\"](.+)[\'\"] ]]; then
        alias_name="${BASH_REMATCH[1]}"
        alias_command="${BASH_REMATCH[2]}"
        echo "| \`$alias_name\` | \`$alias_command\` |" >> "$OUTPUT_FILE"
      fi
    done

    echo "" >> "$OUTPUT_FILE"
  fi
done

# Make the inventory file more readable by adding a navigation section
echo "## Navigation" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Quick links to sections:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for file in "${ALIASES_DIR}"/*.sh; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    # Create anchor links that work in Markdown
    anchor=$(echo "$filename" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
    echo "- [$filename](#$anchor)" >> "$OUTPUT_FILE"
  fi
done

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "Generated by alias-inventory.sh script" >> "$OUTPUT_FILE"

chmod +x "$0"

echo "Alias inventory has been created at $OUTPUT_FILE"
