compute_p9k() {
	# if [ "$NODE_VERSION" != "$(cut -d 'v' -f 2 <<<$(node -v))" ]; then

	TS_ICON='$TS_ICO'
	TS_BG='blue'

	NODE_VERSION="$(cut -d 'v' -f 2 <<<$(node -v))"
	P9K_CUSTOM_NODE="echo -n '\uf898 ' $NODE_VERSION"

	NPM_VERSION="$(npm -v)"
	P9K_CUSTOM_NPM="echo -n '\ue71e ' $NPM_VERSION"

	# TS_VERSION="$(cut -d 'n' -f 2 <<<$(tsc -v))"

	# Customise the p9k prompts
	P9K_LEFT_PROMPT_ELEMENTS=(
		custom_js
		battery
		custom_node
		custom_npm
		custom_tsx
		newline # !!!
		os_icon
		user
		dir
		newline # !!!
		custom_js
		rbenv
		load
		dir_writable
		ssh
		status
		vcs
		custom_tsx
	)

	# fi

	P9K_CUSTOM_NODE_FOREGROUND='black'
	P9K_CUSTOM_NODE_BACKGROUND=$NODE_BG

	P9K_CUSTOM_NPMR_FOREGROUND='black'
	P9K_CUSTOM_NPMR_BACKGROUND=$NPM_BG

	P9K_CUSTOM_NPM_FOREGROUND=$NPM_BG
	P9K_CUSTOM_NPM_BACKGROUND='black'

	P9K_CUSTOM_TS_FOREGROUND='black'
	P9K_CUSTOM_TS_BACKGROUND=$TS_BG

	P9K_CUSTOM_TSR_FOREGROUND=$TS_BG
	P9K_CUSTOM_TSR_BACKGROUND='black'

	P9K_CUSTOM_TSX="echo -n $TS_ICON "
	P9K_CUSTOM_TSX_FOREGROUND='black'
	P9K_CUSTOM_TSX_BACKGROUND=$TS_BG

	P9K_NODE_VERSION_FOREGROUND='black'
	P9K_NODE_VERSION_BACKGROUND='green'

}

TS_ICON=$'\uf071'
JS_BG='yellow'
JS_FG='black'
NODE_BG='green'
NODE_FG='black'
NPM_BG='green'
NPM_FG='black'
TS_BG='yellow'
TS_FG='black'

P9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
P9K_COMMAND_EXECUTION_TIME_PRECISION=4
P9K_CUSTOM_JS="echo -n '\uf81d'"
P9K_CUSTOM_JS_FOREGROUND="$JS_FG"
P9K_CUSTOM_JS_BACKGROUND="$JS_BG"

P9K_RBENV_ALWAYS=true
P9K_RBENV_PROMPT_ALWAYS_SHOW=true
P9K_RBENV_FOREGROUND='red'
P9K_RBENV_BACKGROUND='black'

P9K_COLOR_SCHEME='dark'
P9K_BACKGROUND_JOBS_VERBOSE=false
P9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=false

P9K_TIME_FORMAT='%D{%H:%M:%S}'
P9K_TIME_FOREGROUND='white'
P9K_TIME_BACKGROUND='black'

P9K_RPROMPT_ON_NEWLINE=false
P9K_PROMPT_ON_NEWLINE=false
P9K_PROMPT_ADD_NEWLINE=false

# os_icon
P9K_OS_ICON_BACKGROUND='blue'
P9K_OS_ICON_FOREGROUND='black'

# user - Default
P9K_USER_DEFAULT_ICON=$'\uF415'
P9K_USER_DEFAULT_FOREGROUND='008'
P9K_USER_DEFAULT_BACKGROUND='black'
# user - ROOT
P9K_USER_ROOT_ICON=$'\uf292'
P9K_USER_ROOT_FOREGROUND='red'
P9K_USER_ROOT_BACKGROUND='black'
# user - SUDO
P9K_USER_SUDO_ICON=$'\uF09C'
P9K_USER_SUDO_FOREGROUND='green'
P9K_USER_SUDO_BACKGROUND='black'
# Other icons
P9K_DIR_HOME_ICON=$'\uf015'
P9K_DIR_HOME_SUBFOLDER_ICON=$'\uf115'
P9K_DIR_DEFAULT_ICON=$'\uf07c'
P9K_DIR_ETC_ICON=$'\uf085'
# dir - HOME
P9K_DIR_HOME_BACKGROUND='blue'
P9K_DIR_HOME_FOREGROUND='black'
# dir - HOME_SUBFOLDER
P9K_DIR_HOME_SUBFOLDER_BACKGROUND='blue'
P9K_DIR_HOME_SUBFOLDER_FOREGROUND='black'
# dir - DEFAULT
P9K_DIR_DEFAULT_BACKGROUND='blue'
P9K_DIR_DEFAULT_FOREGROUND='black'
# dir - ETC
P9K_DIR_ETC_BACKGROUND='blue'
P9K_DIR_ETC_FOREGROUND='black'

# Create prompt section
P9K_CUSTOM_PROMPT='echo -n '.''
P9K_CUSTOM_PROMPT_BACKGROUND='blue'
P9K_CUSTOM_PROMPT_FOREGROUND='black'

# Normal Disk Usage
P9K_DISK_USAGE_NORMAL_FOREGROUND='blue'
P9K_DISK_USAGE_NORMAL_BACKGROUND='black'

# Disk Usage: Almost Full
P9K_DISK_USAGE_WARNING_LEVEL='87'
P9K_DISK_USAGE_WARNING_FOREGROUND='red'
P9K_DISK_USAGE_WARNING_BACKGROUND='black'

# Disk Usage: Critically Full
P9K_DISK_USAGE_CRITICAL_LEVEL='92'
P9K_DISK_USAGE_CRITICAL_FOREGROUND='black'
P9K_DISK_USAGE_CRITICAL_BACKGROUND='red'

P9K_DISK_USAGE_NORMAL_ICON=$'\uf7c9'
P9K_DISK_USAGE_WARNING_ICON=$'\uf7c9'
P9K_DISK_USAGE_CRITICAL_ICON=$'\uf7c9'

P9K_DISK_USAGE_NORMAL_ICON_COLOR='blue'
P9K_DISK_USAGE_WARNING_ICON_COLOR='yellow'
P9K_DISK_USAGE_CRITICAL_ICON_COLOR='black'
# Time
P9K_TIME_ICON_COLOR='008'
P9K_TIME_FOREGROUND='008'
P9K_TIME_BACKGROUND='black'

# Customise the Powerlevel9k prompts
P9K_LEFT_PROMPT_ELEMENTS=(
	custom_js
	battery
	custom_tsx
	newline # !!!
	os_icon
	user
	dir
	newline # !!!
	custom_js
	rbenv
	load
	dir_writable
	ssh
	status
	vcs
)

P9K_RIGHT_PROMPT_ELEMENTS=(
	command_execution_time
	ram
	disk_usage
	custom_js
	background_jobs
)

# Load Nerd Fonts with Powerlevel9k theme for Zsh
P9K_MODE='nerdfont-complete'
